import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from './Navbar/Navbar';
import Footer from "./Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "VOLTSTACK",
  description: "Generated by create next app",
  icons: {
    icon: "/fav.svg", // موجودة في public/myicon.png
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* <div className="bg-[#E0E9FB]">
          <Navbar/>
        </div> */}
        {children}
        <div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
